# -*- coding: utf-8 -*-
"""fetch_retrogrades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHDx9dGLp3Gfyt0TiHv6_mRDZRznx4ac
"""

import requests
import json
from datetime import datetime, timedelta

def fetch_retrogrades(start_date, days=7):
    base_url = "https://script.google.com/macros/s/AKfycbyEFPVkHdFU4jmP4yhY3hh5jrRG6uK155177KQrvZ1iQK5oLXa6UPc18G8gE4uq80H9TA/exec?date="
    retrogrades = []

    for i in range(days):
        date = start_date + timedelta(days=i)
        formatted_date = date.strftime('%Y-%m-%d')
        response = requests.get(base_url + formatted_date)

        if response.status_code == 200:
            data = response.json()
            if 'retrogrades' in data:
                retrogrades.extend(data['retrogrades'])
        else:
            print(f"Failed to fetch data for {formatted_date}: {response.status_code}")

    return retrogrades

def save_to_json(data, filename="weekview.json"):
    with open(filename, 'w') as f:
        json.dump(data, f, indent=4)

# Fetch data starting from today
start_date = datetime.now()
retrogrades = fetch_retrogrades(start_date)

# Save the data to a JSON file
save_to_json({"retrogrades": retrogrades})

# Print the fetched data for verification
print(json.dumps({"retrogrades": retrogrades}, indent=4))